/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as JoinRoomImport } from './routes/join-room'
import { Route as CreateRoomImport } from './routes/create-room'
import { Route as IndexImport } from './routes/index'
import { Route as RoomRoomIdImport } from './routes/room/$roomId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const JoinRoomRoute = JoinRoomImport.update({
  id: '/join-room',
  path: '/join-room',
  getParentRoute: () => rootRoute,
} as any)

const CreateRoomRoute = CreateRoomImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoomRoomIdRoute = RoomRoomIdImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-room': {
      id: '/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof CreateRoomImport
      parentRoute: typeof rootRoute
    }
    '/join-room': {
      id: '/join-room'
      path: '/join-room'
      fullPath: '/join-room'
      preLoaderRoute: typeof JoinRoomImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/settings': typeof SettingsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/settings': typeof SettingsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/settings': typeof SettingsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-room' | '/join-room' | '/settings' | '/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-room' | '/join-room' | '/settings' | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/create-room'
    | '/join-room'
    | '/settings'
    | '/room/$roomId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoomRoute: typeof CreateRoomRoute
  JoinRoomRoute: typeof JoinRoomRoute
  SettingsRoute: typeof SettingsRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoomRoute: CreateRoomRoute,
  JoinRoomRoute: JoinRoomRoute,
  SettingsRoute: SettingsRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-room",
        "/join-room",
        "/settings",
        "/room/$roomId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-room": {
      "filePath": "create-room.tsx"
    },
    "/join-room": {
      "filePath": "join-room.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/room/$roomId": {
      "filePath": "room/$roomId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
